In [4]:
import pandas as pd
import numpy as np

In [9]:
data = np.array([
    [1,'Alice',30],
    [2,'Bob',25],
    [3,'Charlie',35]])

df = pd.DataFrame(data)
df = pd.DataFrame(data, columns = ['ID','Name','Age'])

print(df)

  ID     Name Age
0  1    Alice  30
1  2      Bob  25
2  3  Charlie  35

In [56]:
df = pd.read_csv('C:/Users/User/Downloads/국영수.csv', encoding='utf-8', header=0)
# header None은 컬럼 명이 숫자. header 0 은 기본 변수명을 보장
display(df)

   국어  영어  수학 체육
0  50  88  21  상
1  41  87  54  중
2  85  65  84  상
3  61  85  13  중
4  54  41  21  하
5  84  47  87  하
6  77  98  65  상
7  87  58  54  중
8  54  22  78  히

In [31]:
df.shape

(9, 4)

In [32]:
df.columns

Index(['국어', '영어', '수학', '체육'], dtype='str')

In [57]:
df.dtypes

국어    int64
영어    int64
수학    int64
체육      str
dtype: object

In [34]:
df.describe()

              국어         영어         수학
count   9.000000   9.000000   9.000000
mean   65.888889  65.666667  53.000000
std    17.467430  25.729361  28.583212
min    41.000000  22.000000  13.000000
25%    54.000000  47.000000  21.000000
50%    61.000000  65.000000  54.000000
75%    84.000000  87.000000  78.000000
max    87.000000  98.000000  87.000000

In [35]:
df.isnull().sum()

국어    0
영어    0
수학    0
체육    0
dtype: int64

In [36]:
df['체육'].value_counts()

체육
상    3
중    3
하    2
히    1
Name: count, dtype: int64

In [37]:
df["체육"]

0    상
1    중
2    상
3    중
4    하
5    하
6    상
7    중
8    히
Name: 체육, dtype: str

In [39]:
df["합계"] = df["국어"] + df["영어"] + df["수학"]

df

   국어  영어  수학 체육   합계
0  50  88  21  상  159
1  41  87  54  중  182
2  85  65  84  상  234
3  61  85  13  중  159
4  54  41  21  하  116
5  84  47  87  하  218
6  77  98  65  상  240
7  87  58  54  중  199
8  54  22  78  히  154

In [41]:
columns = ['체육','합계']
select_columns = df[columns]
select_columns

  체육   합계
0  상  159
1  중  182
2  상  234
3  중  159
4  하  116
5  하  218
6  상  240
7  중  199
8  히  154

In [58]:
data = {
    'A':[1,2,3,4],
    'B':[4.1,3.5,2.1,5.7],
    'C':['one','two','three','four']
}
df = pd.DataFrame(data)
df

   A    B      C
0  1  4.1    one
1  2  3.5    two
2  3  2.1  three
3  4  5.7   four

In [50]:
df['A'] = df['A'].astype(float)
df['A'].dtype
df['A']

0    1.0
1    2.0
2    3.0
3    4.0
Name: A, dtype: float64

In [51]:
df['B'] = df['B'].astype(int)
df['B'].dtype
df['B']

0    4
1    3
2    2
3    5
Name: B, dtype: int64

In [52]:
df['A'] = df['A'].astype('str')
df['A'].dtype
df['A']

0    1.0
1    2.0
2    3.0
3    4.0
Name: A, dtype: str

In [53]:
df['C'] = df['C'].astype('category')
df['C'].dtype
df['C']

0      one
1      two
2    three
3     four
Name: C, dtype: category
Categories (4, str): ['four', 'one', 'three', 'two']

In [60]:
df = df.rename(columns={
    'A':'일',
    'B':'이',
    'C':'삼'})
df

   일    이      삼
0  1  4.1    one
1  2  3.5    two
2  3  2.1  three
3  4  5.7   four

In [62]:
data = {
    'Numeric1':[1,np.nan,3,4],
    'Numeric2':[5,6,np.nan,8.2],
    'Category':['dog',np.nan,'cat','dog']
}
df = pd.DataFrame(data)
df

   Numeric1  Numeric2 Category
0       1.0       5.0      dog
1       NaN       6.0      NaN
2       3.0       NaN      cat
3       4.0       8.2      dog

In [63]:
A=df.select_dtypes(include=["number"]).columns
df[A]

   Numeric1  Numeric2
0       1.0       5.0
1       NaN       6.0
2       3.0       NaN
3       4.0       8.2

In [64]:
B=df.select_dtypes(include=['object','category']).columns #object가 있을수도 있고 그래서 2개적음
df[B]

C:\Users\User\AppData\Local\Temp\ipykernel_16920\546220753.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  B=df.select_dtypes(include=['object','category']).columns

  Category
0      dog
1      NaN
2      cat
3      dog

In [67]:
df[A].fillna(df[A].median())

   Numeric1  Numeric2
0       1.0       5.0
1       3.0       6.0
2       3.0       6.0
3       4.0       8.2

In [68]:
df1 = pd.DataFrame({
    'a':['a0','a1','a2','a3'],
    'b':['b0','b1','b2','b3'],
    'c':['c0','c1','c2','c3']
})

df2 = pd.DataFrame({
    'a':['a2','a3','a4','a5'],
    'b':['b2','b3','b4','b5'],
    'c':['c2','c3','c4','c5'],
    'd':['d2','d3','d4','d5']
})

In [69]:
pd.concat([df1,df2],axis=0)

    a   b   c    d
0  a0  b0  c0  NaN
1  a1  b1  c1  NaN
2  a2  b2  c2  NaN
3  a3  b3  c3  NaN
0  a2  b2  c2   d2
1  a3  b3  c3   d3
2  a4  b4  c4   d4
3  a5  b5  c5   d5

In [70]:
pd.concat([df1,df2],axis=1)

    a   b   c   a   b   c   d
0  a0  b0  c0  a2  b2  c2  d2
1  a1  b1  c1  a3  b3  c3  d3
2  a2  b2  c2  a4  b4  c4  d4
3  a3  b3  c3  a5  b5  c5  d5

In [71]:
pd.concat([df[A],df[B]],axis=1)

   Numeric1  Numeric2 Category
0       1.0       5.0      dog
1       NaN       6.0      NaN
2       3.0       NaN      cat
3       4.0       8.2      dog

In [72]:
df[:2]

   Numeric1  Numeric2 Category
0       1.0       5.0      dog
1       NaN       6.0      NaN